"""initial schema

Creates all tables from the SQLAlchemy metadata. Subsequent schema changes
should use autogenerated, hand-reviewed migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01
"""
from __future__ import annotations

from alembic import op

from app.core.database import Base
import app.models  # noqa: F401  (register all models on the metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
